---
title: "Cherry by Nico Walker"
date: 01/07/19 
#output: html_document
images: 
  - cherry_cover.jpg
---

My brother sent me this one for christmas.


###Impression/Comparison
This book is what Charles Bukowski would’ve written if he went to war in the 2000s instead of the Postal Service in the 60s. As I read through both stories I wondered “what the hell is the point of all this?”  To both of their credits, I didn’t get the impression that either author would claim that it’s very easy to glean “a point” out of their stories (or life?). Walker says something to this effect in the prepilogue[^1].

“I’m twenty-five years old and I don’t understand what it is people do.  It’s as if all this were built on nothing, and nothing were holding this together.” (page 7)

However! upon nearing the end of Cherry I de-coupled Bukowski and Walker in my brain as I realized that this book does give a pretty solid answer to at least one good question, which is: “How do you become a scumbag?” (page …). The Post Office is more like, “What does a scumbag do all day for 17 years?” 

###Summary
The story follows the main character. He’s a punk that takes a little bit of drugs, then he goes to war which is “gory as fuck, not making sense” (p 138), starts taking more drugs, returns from war, becomes a dope fiend, runs out of money, becomes a bank robber to fuel his fiendery, gets busted. All (or mostly) while he’s madly in love with Emily. 


###Seemingly Contextless
The story is one from the front lines of both the war in Iraq and the american opioid crisis. The irony is that you come away from the book knowing almost nothing about either. Well, nothing but the very very gory details. In war, he and his comrades carry out seemingly contextless missions. It’s as if he had no interest in knowing what their purpose was, or he had no interest in writing about their purpose. [P175] Then we get to the opioids abuse. If you were none the wiser, you’d have no idea that this one man’s opioid story is taking place during a nationwide opioid epidemic.  Then again, that one man probably didn’t have any idea either.
 
###The Trap
This is my favorite line in the book:
“I understand.  Believe me, I understand. I really do. And you’re right. And I’m sorry. I feel it too. It’s just we’re so fucked and I don’t know how we’re going to get out from under this thing so all I can do is try and hold things together the way they are. We have so much to do all the time and it’s like when can we get sick for a month, you know? When will we have time to do that? [when you go to jail] It’s a fucking trap, you know?”

###Absolutely Brutal With a Tasteful Touch of Amusing
I would often look up from reading this book and mutter aloud to myself “bloody f**king hell” (i.e. the setting) out of sadness and disgust.  At the same time, however, I felt myself tickled by some of his amusing/smart-assey imagery: 

“The big room smelled like balls (unwashed) and feet (ditto) and open ass (regardless)” (p 55)
“He was a stout man, built like a coconut.” (p 124)
“Lieutenant Evans had the sort of intentions with which you can pave a road to hell.” (p 169)


###More Quotes
“About Emily I guess I was deluding myself. Somewhat knowingly. Or just knowingly. Or maybe I didn’t know. I can’t remember.” P 158

“I need money I need drugs I need love all the above” Eli Forsman song.

“Days came like dead moths on the bathroom counter.”

“About Emily I guess I was deluding myself. Somewhat knowingly. Or just knowingly. Or maybe I didn’t know. I can’t remember.” page 157.

This quote reminds me of the cover of the book and L’Etranger.
“Then came another hot bullshit day. The heat and the light made your brain skip when you tried to hold a thought. Thoughts wouldn’t come in a straight line, and you saw translucent red stars.” page 168

[^1]: Prepilogue: The prologue which takes place at the end of the story.