---
title: "Pincher Martin by William Golding"
images:
  - pincher_martin_cover.jpg
---

Pincher Martin by William Golding
05/23/2018

I found this book in a ski bag I hadn’t touched in a couple years. The last Golding book I read was Lord of the Flies on a ski trip at Tremblant with Dad in ~2010. I’m beginning to see a pattern emerge...
I think I’ve been writing these reviews as if the reader has already read the book. In any case: <span style="color:red">*SPOILER ALERT!*</span>  
.  
.  
.  
.  
.  
.  
.  
.  
.  
This entire story is a ruse until the very last line.  For ~13 out of 14 chapters, Christopher Hadley “Pincher” Martin spends his time on a rock in the middle of the Atlantic after being sent off of a torpedoed ship. The very last uttered sentence reveals that he actually died immediately after being torpedoed: "he didn't even have time to kick off his seaboots".  When I finished the book I thought, “Wait a second was that entire story a delusion in the mind of a drowning man?... no it couldn’t be. Those seaboots were about something else that I don’t understand.” It took me until reading the wikipedia summary to really believe it.  

So, his entire time on the rock was a delusion. Some things that I notice upon looking back at the story with the knowledge that it was all a purgatorial hallucination (by the nature of the book all you can do is look back at it with the appropriate knowledge).


Themes of being eaten ran through Pincher’s decay into madness.  The islet he was on was a part of a series of 5 or 6 that together formed a row of teeth. He had been eaten by the sea. 
He kept seeing his arms/hands as lobsters.  Not sure what that was about. Maybe Golding just had to fit something in with the title of the book.
He had flashbacks of being rejected by a woman named Mary, and his maniacal reaction: driving recklessly and threatening to kill her. He also had flashbacks of his friend Nate confession his plan to marry Mary. He also had flashbacks of being on the boat just before it exploded. These flashbacks served the purpose of showing the reader how he got here and perhaps displaying Pincher’s mind starting to turn on itself or give up a little or latch on to identity. 
At the end of his tenure ‘pon the rock, he kept feeling like he had realized something, but his ego tried to protect him from it. He felt it as the sensation of a shovel striking a hard tin box as it swung down for a dig. This seems to be an analogy for his descent into madness being a (harrowing) journey toward the truth: Christopher Martin is a dead man floating through the ocean.
There were times when I was encouraged by Pincher’s utter will to survive. Now that I know he was basically/actually dead at the time, I’m one part disenchanted (“Aw what? He’s been toast the whole time?”) and two parts reinvigorated (“The will to survive cares not that it’s host has already not survived!”). I must say that I really thought he was going to be rescued. 

All in all, just as dark as Lord of the Flies in the meat of the book, but less uplifting at the end. Not that LOTF has a particularly uplifting end, but at least it gives you a sigh of relief with a touch of comedy (sorry Golding- had to make the comparison).
