---
title: "Persepolis"
images: 
  - persepolis_cover.png
---
Persepolis by Marjane Satrapi 
February 2019

Teta Anne sent me this one for christmas. I crushed it on the plane ride to Denver.

##The Medium
On one hand, a graphic novel (told through a child’s eyes) is a limiting way to learn about a topic as complicated as the Iranian revolution. On the other hand, it makes the delivery of such a story easily accessible and entertaining.  
**How the medium was limiting**: For the first few sections I found myself flipping back and forth between the introduction (which provided 2 pages of historical context), and the story to try to figure out what the hell was going on.  Between Reza Shah, the brits, the prime minister, the revolutionaries, and many others, it was easy to get all the main players (and their motives) confused when each of them got a few panels of description. Happily, once I got about halfway through, I felt roughly up to speed.  
**How the medium was effective**: The father’s explanation of the end of the Iran-Iraq War and Mujahideen’s unwelcomed entrance into Iran and eventual demise was very informative and interesting. True, there are certainly details of this that go unexplained. How did the Mujahideens end up striking a deal with Saddam Hussein? How were the Mujahideen defeated by the Guardians of the Revolution and the army? What were the conditions of the armistice? The list goes on, but the level of detail was pretty ideal for putting the reader in the author’s shoes. It’s important also to remember that this is a story, not a history book, whose purpose is to make the reader feel, not just understand.
In any case, I assume Satrapi is aware of the trade-offs of broaching a complicated topic with a graphic novel as she spends her childhood reading one called Dialectic Materialism. 

##Inflection Points
People and systems are often most vulnerable to influence at times of great change. The Iranian Revolution introduced an opportunity for significant change in the country. Islamic organizations involved in the overthrow of the Shah took advantage of this opportunity and managed to channel the momentum of the revolution into their own hands, much to the chagrin of Satrapi’s father and the rest of the leftist revolutionaries: “It’s incredible. The revolution is a leftist revolution, and the republic wants to be called Islamic” (page …). 
A kid moving to a different school is susceptible to pick up new hobbies, styles, and friends. That’s probably why we see Marjane getting into sex, drugs, and general punkery when she moves to Europe to study. With a clean slate, you can be anyone.

##Political Ignorance
Marjane meets Shirin, the daughter of an old Iranian family friend that moved to Vienna. Shirin likes talking about little girl stuff like lipstick and earmuffs. 
“What a traitor! While people were dying in our country, she was talking to me about trivial things!” (page 156)
This reminds me of what my Iranian friend Hamed told me on a hike once. People in America often don’t know very much about politics and world events, because they’re insulated. Geopolitics doesn’t affect their daily lives. When the US levies sanctions on Iran, prices go up and everyone has to tighten their belts. As a result, even the least educated in Iran are relatively informed about current events.


##Funniest Part
Marjane discusses the shame she felt for getting into drug use. “Becoming a vegetable was out of the question” (page 192). On this page is a hysterical drawing of a squash with a face. 

##Between a Rock and a Hard Place 
Toward the end of Marjane’s tenure in Vienna, she reflects on her time abroad: “I was a ashamed of not becoming someone, but a mediocre nihilist” (p 244). Immediately, however, upon returning to Iran, she feels repressed as the customs agent asks her about her travels and tells her to fix her hijab (p 246). She’s a woman without a place to call home.

##Through a Child’s Eyes
I like when authors (who are usually adults) effectively capture the feeling of being a child (often it’s a feeling of hopeless smallness in the face of (more like the knees of) all-knowing adults).  Marjane does this when she shows herself a young girl trying to follow a conversation happening between her mother and grandmother (p ...). The speech bubbles are filled with illegible scribbles. Charlie Brown cartoons do a similar thing where all adults say is “womp womp womp womp…”. As a youngster, I often sat in the back seat listening to public radio news and the subsequent conversations that would happen between my parents. It always sounded like gibberish to me.


##A point of order
I liked the way each section was named.  The title would refer to a small but interesting characteristic of the story told. For example, in the chapter called Sheep: Satrapi reveals that the leftist revolutionaries who were released after the Shah’s exiling eventually fled or were imprisoned and/or killed. One of the families in question escaped with a herd of sheep. 
I challenged myself to remember the name of the section I was reading. I remembered about half the titles by the end of each section. 

##Parents, Their Children, and Tradition
At the end of the book Marjane prepares to leave her home country of Iran once and for all. Her parents’ reaction: “Well, we’re very happy with your decision. You weren’t made to live here. We Iranians, we’re crushed not only by the government, but by the weight of our traditions!” Her parents hold in their hearts two seemingly incongruous convictions: 
Their daughter must leave.
They must stay.
This is a pretty beautiful moment. A little sad, to be sure, but with a helping of hopefulness. 
Cause the times, they are a-changin.
