---
title: "Soonish"
images: 
  - soonish_cover.jpg
---
Soonish: Ten Emerging Technologies That'll Improve and/or Ruin Everything
By Zach and Kelly Weinersmith

This book is written by the author of my favorite webcomic, Saturday Morning Breakfast Cereal, along with his wife.  So, I had to get the book when I heard it was being written. It’s full of humorous analogies used to explain scientific phenomena, a single-panel comic every couple pages, and not to mention, some actual information/speculations about the future.

Because of the format of the book, it was easy to finish a chapter with a general idea about the topic, but a major lack of details. For example, they would often say things like “You’ll remember Dr. Alfred from the last chapter was working on programmable matter…”. I would almost certainly not remember Dr. Alfred. Partly because there were about 10 scientists discussed per chapter, and partly because I didn’t treat the book as an learning experience as much as I did treat it as an entertainment experience. 

That said, a few specific nuggets along the way stuck pretty hard.  The most memorable of them being the story of Mr. Bull.  Well, I only just remembered his last name, but after a quick Google search- it’s Gerald Bull.  This guy was a Canadian engineer working on a joint US-Canada project. Eventually, it was closed down, so in his lifelong pursuit to make a giant cannon intended to send projectiles into space, he took a job with Sadaam Hussein. Eventually-er, he was assassinated. 

I’m not sure if this was a book review, or an analysis of my poor short-term memory. In any case, hopefully that memory issue will be cleaned up by a brain-computer interface soon...ish.


###Now to see if I can remember all ten technologies while I type this out...

Easy Space Access (and mining)

Programmable Matter
Augmented Reality


Biology Editing
Precision Medicine
Brain-Computer Interfaces

###I missed...
Robot builders
Fusion Power 
Synthetic Biology
Bioprinting
